# Generated by Django 3.1.3 on 2020-11-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signals',
            name='id',
        ),
        migrations.AddField(
            model_name='signals',
            name='signal_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
