# Generated by Django 3.1.3 on 2020-11-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0002_auto_20201111_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signals',
            name='signal_id',
        ),
        migrations.AddField(
            model_name='signals',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
